# Generated by Django 4.0 on 2022-08-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnid', models.IntegerField(db_index=True, unique=True, verbose_name='Hacker News Item Id')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Option', 'Pollopt')], max_length=15)),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('is_api_created', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnid', models.IntegerField(db_index=True, unique=True, verbose_name='Hacker News Item Id')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Option', 'Pollopt')], max_length=15)),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('is_api_created', models.BooleanField(default=False)),
                ('parts', models.JSONField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnid', models.IntegerField(db_index=True, unique=True, verbose_name='Hacker News Item Id')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Option', 'Pollopt')], max_length=15)),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('is_api_created', models.BooleanField(default=False)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnid', models.IntegerField(db_index=True, unique=True, verbose_name='Hacker News Item Id')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Option', 'Pollopt')], max_length=15)),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('is_api_created', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_kids', to='news.poll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnid', models.IntegerField(db_index=True, unique=True, verbose_name='Hacker News Item Id')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Option', 'Pollopt')], max_length=15)),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('is_api_created', models.BooleanField(default=False)),
                ('parent_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('parent_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
