# Generated by Django 4.0 on 2022-08-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(default='Comment', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default='Job', max_length=15),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(default='Poll', max_length=15),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_parts', to='news.poll'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='type',
            field=models.CharField(default='Poll Option', max_length=15),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(default='Story', max_length=15),
        ),
    ]
