# Generated by Django 4.0 on 2022-08-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_text_alter_comment_type_alter_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
